--[[
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
	SimpleTeleporters Config File

Short tutorial:
	To the left you see the variable names
	After the equal sign, you see the value which you can change
	
Do not delete anything, this will break the mod.

### Variable Definitions ###

	TIER_X_BUFFER_CAPACITY
		Defines how much buffer capacity the teleporter has.
		In MegaJoule (MJ)
	TIER_X_TELEPORT_POWER
		Defines how much power the teleporter needs to teleport.
		In MegaJoule (MJ)
	TIER_X_DISTANCE
		Defines the distance the teleporter can handle.
		In Tiles (1 Tile = Size of one belt)
	TIER_X_COOLDOWN
		The cooldown per tier.
		In Seconds

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
]]--

-- General Settings
MSG_OUTPUT_MODE = 2 -- 1 is FlyingText; 2 is Chat
FLOW_DIVIDER = 60 -- Global Dividier for calculation Flow limit values

-- TIER 1
TIER_01_BUFFER_CAPACITY = 60
TIER_01_TELEPORT_POWER = 15
TIER_01_DISTANCE = 200
TIER_01_FLOW_LIMIT = TIER_01_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_01_COOLDOWN = 10

--TIER 2
TIER_02_BUFFER_CAPACITY = 120
TIER_02_TELEPORT_POWER = 29.1
TIER_02_DISTANCE = 400
TIER_02_FLOW_LIMIT = TIER_02_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_02_COOLDOWN = 12

--TIER 3
TIER_03_BUFFER_CAPACITY = 180
TIER_03_TELEPORT_POWER = 42.3
TIER_03_DISTANCE = 600
TIER_03_FLOW_LIMIT = TIER_03_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_03_COOLDOWN =14

--TIER 4
TIER_04_BUFFER_CAPACITY = 240
TIER_04_TELEPORT_POWER = 54.6
TIER_04_DISTANCE = 800
TIER_04_FLOW_LIMIT = TIER_04_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_04_COOLDOWN = 16

--TIER 5
TIER_05_BUFFER_CAPACITY = 300
TIER_05_TELEPORT_POWER = 66
TIER_05_DISTANCE = 1000
TIER_05_FLOW_LIMIT = TIER_05_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_05_COOLDOWN = 18

--TIER 6
TIER_06_BUFFER_CAPACITY = 360
TIER_06_TELEPORT_POWER = 76.5
TIER_06_DISTANCE = 1200
TIER_06_FLOW_LIMIT = TIER_06_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_06_COOLDOWN = 20

--TIER 7
TIER_07_BUFFER_CAPACITY = 420
TIER_07_TELEPORT_POWER = 86.1
TIER_07_DISTANCE = 1400
TIER_07_FLOW_LIMIT = TIER_07_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_07_COOLDOWN = 22

--TIER 8
TIER_08_BUFFER_CAPACITY = 480
TIER_08_TELEPORT_POWER = 94.8
TIER_08_DISTANCE = 1600
TIER_08_FLOW_LIMIT = TIER_08_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_08_COOLDOWN = 24

--TIER 9
TIER_09_BUFFER_CAPACITY = 540
TIER_09_TELEPORT_POWER = 102.6
TIER_09_DISTANCE = 1800
TIER_09_FLOW_LIMIT = TIER_09_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_09_COOLDOWN = 27

--TIER 10
TIER_10_BUFFER_CAPACITY = 600
TIER_10_TELEPORT_POWER = 105
TIER_10_DISTANCE = 2000
TIER_10_FLOW_LIMIT = TIER_10_BUFFER_CAPACITY / FLOW_DIVIDER
TIER_10_COOLDOWN = 30