data:extend({
	-- Teleporter Tier Items
	{
		type = "item",
		name = "Teleporter_Tier01",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Tier01]",
		place_result="Teleporter_Tier01",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier02",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "b[Teleporter_Tier1]-c[Teleporter_Tier02]",
		place_result="Teleporter_Tier02",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier03",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "c[Teleporter_Tier2]-d[Teleporter_Tier03]",
		place_result="Teleporter_Tier03",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier04",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "d[Teleporter_Tier3]-e[Teleporter_Tier04]",
		place_result="Teleporter_Tier04",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier05",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "e[Teleporter_Tier4]-f[Teleporter_Tier05]",
		place_result="Teleporter_Tier05",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier06",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "f[Teleporter_Tier5]-g[Teleporter_Tier06]",
		place_result="Teleporter_Tier06",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier07",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "g[Teleporter_Tier6]-h[Teleporter_Tier07]",
		place_result="Teleporter_Tier07",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier08",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "h[Teleporter_Tier7]-i[Teleporter_Tier08]",
		place_result="Teleporter_Tier08",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier09",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "i[Teleporter_Tier8]-j[Teleporter_Tier09]",
		place_result="Teleporter_Tier09",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Tier10",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/icon.png",
		flags = { "goes-to-quickbar" },
		order = "j[Teleporter_Tier9]-k[Teleporter_Tier10]",
		place_result="Teleporter_Tier10",
		stack_size= 2,
	},
	
	
	-- Teleporter Tier UPgrade Items
	{
		type = "item",
		name = "Teleporter_Upgrade_02",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/red/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_02]",
		place_result="Teleporter_UpgradeEntity_02",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_03",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/lime/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_03]",
		place_result="Teleporter_UpgradeEntity_03",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_04",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/green/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_04]",
		place_result="Teleporter_UpgradeEntity_04",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_05",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/mint/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_05]",
		place_result="Teleporter_UpgradeEntity_05",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_06",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/pink/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_06]",
		place_result="Teleporter_UpgradeEntity_06",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_07",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/purple/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_07]",
		place_result="Teleporter_UpgradeEntity_07",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_08",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/cyan/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_08]",
		place_result="Teleporter_UpgradeEntity_08",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_09",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/light-blue/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_09]",
		place_result="Teleporter_UpgradeEntity_09",
		stack_size= 2,
	},
	{
		type = "item",
		name = "Teleporter_Upgrade_10",
		subgroup = "SimpleTeleporters",
		icon = "__SimpleTeleporters__/graphics/tiers/dark-blue/upgrade.png",
		flags = { "goes-to-quickbar" },
		order = "a[items]-b[Teleporter_Upgrade_10]",
		place_result="Teleporter_UpgradeEntity_10",
		stack_size= 2,
	},
})